Grupos/Grupos/urls.py
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('competencias/', views.competencias, name='competencias'),
    path('competencias/<int:competencia_id>/', views.detalles_competencia, name='detalles_competencia'),
    path('competencias/<int:competencia_id>/grupos/', views.grupos, name='grupos'),
    path('competencias/<int:competencia_id>/jugadores/', views.jugadores, name='jugadores'),
    path('sortear_grupos/', views.sortear_grupos, name='sortear_grupos'),
    path('competencias/<int:competencia_id>/partidos/', views.partidos, name='partidos'),
    path('competencias/<int:competencia_id>/generar_partidos/', views.generar_partidos, name='generar_partidos'),

]

Grupos/myapp/models.py
from django.db import models


class Grupo(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Equipo(models.Model):
    nombre = models.CharField(max_length=100)
    grupos = models.ManyToManyField(Grupo, related_name='equipos', blank=True)

    def __str__(self):
        return self.nombre


class Partido(models.Model):
    fecha = models.DateTimeField()
    hora = models.TimeField(default='00:00:00')
    resultado = models.CharField(max_length=100)
    equipo_local = models.ForeignKey(Equipo, related_name='partidos_local', on_delete=models.CASCADE)
    equipo_visitante = models.ForeignKey(Equipo, related_name='partidos_visitante', on_delete=models.CASCADE)


class Jugador(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    edad = models.IntegerField()
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Competencia(models.Model):
    nombre = models.CharField(max_length=100)
    numero_grupos = models.IntegerField(default=0)
    grupos = models.ManyToManyField(Grupo)

    def __str__(self):
        return self.nombre

Grupos/myapp/views.py
from datetime import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Competencia, Grupo, Equipo, Partido, Jugador
from .utils import sortear_equipos_en_grupos, generar_programacion_partidos


# Create your views here.

def generar_partidos(request, competencia_id):
    competencia = get_object_or_404(Competencia, pk=competencia_id)
    generar_programacion_partidos(competencia_id)

    # Redireccionar a la vista 'partidos'
    return redirect(reverse('partidos', kwargs={'competencia_id': competencia_id}))


def sortear_grupos(request):
    competencias = Competencia.objects.all()
    for competencia in competencias:
        sortear_equipos_en_grupos(competencia.id)

    return redirect('grupos', pk=   competencia.id)


def home(request):
    competencias = Competencia.objects.all()
    return render(request, 'home.html', {'competencias': competencias})


def competencias(request):
    competencias = Competencia.objects.all()
    return render(request, 'competencias.html', {'competencias': competencias})


def detalles_competencia(request, competencia_id):
    competencia = get_object_or_404(Competencia, pk=competencia_id)
    return render(request, 'detalles_competencia.html', {'competencia': competencia})


def grupos(request, competencia_id):
    competencia = Competencia.objects.get(pk=competencia_id)
    grupos = competencia.grupos.all()
    return render(request, 'grupos.html', {'grupos': grupos})


def partidos(request, competencia_id):
    competencia = get_object_or_404(Competencia, pk=competencia_id)
    grupos = competencia.grupos.all()

    # Obtenemos todos los partidos relacionados con los grupos de la competencia
    partidos = Partido.objects.filter(equipo_local__in=grupos.values('equipos__id'),
                                      equipo_visitante__in=grupos.values('equipos__id'))

    return render(request, 'partidos.html', {'competencia': competencia, 'partidos': partidos})


def jugadores(request, competencia_id):
    competencia = get_object_or_404(Competencia, pk=competencia_id)
    jugadores = Jugador.objects.filter(equipo__in=competencia.grupos.all())
    return render(request, 'jugadores.html', {'competencia': competencia, 'jugadores': jugadores})

Grupos/myapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                </div>
            </div>
        </div>
    </nav>
</header>

<main class="p-5">
    {% block content %}

    {% endblock %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

Grupos/myapp/templates/detalles_competencia.html
{% extends 'base.html' %}
{% block content %}

    <h1 class="text-center">{{ competencia.nombre }}</h1>

    <ul class="nav justify-content-end">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'grupos' competencia.id %}">Grupos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'partidos' competencia.id %}">Partidos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Equipos</a>
        </li>
    </ul>





{% endblock %}
```

Grupos/myapp/templates/grupos.html
{% extends 'base.html' %}
{% block content %}

    <h1>Grupos</h1>
    <br>
    <form action="{% url 'sortear_grupos' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-primary">Sortear Grupos</button>
    </form>
    <br>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for grupo in grupos %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ grupo.nombre }}</h5>
                            <div class="card">
                                <ul class="list-group list-group-flush">
                                    {% for equipo in grupo.equipos.all %}
                                        <li class="list-group-item">{{ equipo.nombre }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

Grupos/myapp/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <h1>Home</h1>
    <br>
    {% for competencia in competencias %}
        <div class="card">
            <div class="card-header">
                Futbol
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ competencia.nombre }}</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="{% url 'detalles_competencia' competencia.id %}" class="btn btn-primary">Ver Detalles</a>
            </div>
        </div>
    {% endfor %}

{% endblock %}

Grupos/myapp/templates/partidos.html
{% extends 'base.html' %}
{% block content %}

    <h1>Partidos por Grupos</h1>
    <br>
    <form action="{% url 'generar_partidos' competencia.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Generar Partidos</button>
    </form>
    <br>
    <h1>Programación de Partidos</h1>

    {% for grupo in grupos %}
        <h2>{{ grupo.nombre }}</h2>
        {% for partido in grupo.partido_set.all %}
            <p>Equipo Local: {{ partido.equipo_local.nombre }}</p>
            <p>Equipo Visitante: {{ partido.equipo_visitante.nombre }}</p>
            <p>Fecha: {{ partido.fecha }}</p>
            <br>
        {% endfor %}
    {% endfor %}

{% endblock %}